Feature/yifan/accordion
Azumydori/Nebula-SpaceMarket pull request #13
Opened 2021-08-30 14:22 UTC by YifanYes

Terminado acordeon, y lista la pagina de faq

2021-08-30 15:04 UTC, JimenaEB requested changes
De que trata esta PR? Por qué hay tantas cosas juntas?

2021-08-30 15:04 UTC, JimenaEB commented on src/api/admin.py
> +>>>>>>> 102335576cefe1f5deb90c4d5ee089d6fcfbdaa4
cuidado esto aquí

2021-08-30 15:48 UTC, YifanYes commented
> De que trata esta PR? Por qué hay tantas cosas juntas?

Lo importante solo es la vista de las FAQ y el componente acordeon

2021-08-30 15:48 UTC, YifanYes commented on src/api/admin.py
> +>>>>>>> 102335576cefe1f5deb90c4d5ee089d6fcfbdaa4
Si, es que este admin esta desactualizado

2021-09-01 14:29 UTC, YifanYes commented
Voy a hacer una pull request nueva para que no tenga tantos archivos modificados ni conflictos

2021-09-01 14:29 UTC, closed without merging