Register connected with backend succesfully. jesus cristo
Azumydori/Nebula-SpaceMarket pull request #14
Opened 2021-08-30 15:34 UTC by Azumydori

2021-09-01 13:44 UTC, JimenaEB requested changes

2021-09-01 13:44 UTC, JimenaEB commented on src/api/models.py
> +
Ojo no sobreescribas la base de datos, mergeate main y que esto no cambie

2021-09-01 13:44 UTC, JimenaEB commented on src/api/models.py
> +   '''
borra este trozo

2021-09-01 13:44 UTC, JimenaEB commented on src/api/models.py
> +class Order(db.Model):
Ojo que de aquí para abajo tampoco debería estar

2021-09-01 13:44 UTC, JimenaEB commented on src/api/routes.py
> +    print("estas aqui")
borra los prints

2021-09-01 13:44 UTC, JimenaEB commented on src/api/routes.py
> +@api.route('/account/<int:id>', methods = ['PATCH'])
de aquí para abajo tampoco te hace falta para el registro

2021-09-01 13:44 UTC, JimenaEB commented on src/front/js/component/footer.js
> +		<p>TONTO EL QUE LO LEA</p>
borra esto

2021-09-01 13:44 UTC, JimenaEB commented on src/front/js/component/registerpage.js
> +					N
cuidado esta N

2021-09-01 13:45 UTC, JimenaEB commented
Cuiado con main y los conflictos que tienes. Mergeate main en tu rama siempre antes de hacer una PR

2021-09-02 09:15 UTC, Azumydori commented
Cerrada por hacer actualizaciones

2021-09-02 09:15 UTC, closed without merging